version: '3.4'

services:
  apigatewayservice:
    image: apigatewayservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: developement
    ports:
      - 3001:3001
